# Generated by Django 4.0.5 on 2022-06-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('price_usd', models.FloatField()),
                ('delivery_date', models.DateField()),
                ('price_rub', models.FloatField(null=True)),
            ],
        ),
    ]
